services:
  - type: web
    name: telegram-album-bot
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        value: "THAY_TOKEN_CỦA_BẠN_VÀO_ĐÂY"
